<a href="https://colab.research.google.com/github/Husnain2692/Python_Learning_with_Apna_College/blob/main/Lec15_Pandas_Merge_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the Pandas library for data manipulation
import pandas as pd

# Define the first dictionary containing student names and marks
data1 = {
    "Name": ["Ali", "Sara"],
    "Marks": [85, 92]
}

# Convert the dictionary 'data1' into a Pandas DataFrame
df1 = pd.DataFrame(data1)

# Display the first DataFrame
print(df1)

   Name  Marks
0   Ali     85
1  Sara     92

In [2]:
data2 = {
    "Name": ["John", "Emma"],
    "Marks": [78, 95]
}

# Convert the dictionary 'data2' into a Pandas DataFrame
df2 = pd.DataFrame(data2)

# Display the second DataFrame
print(df2)

   Name  Marks
0  John     78
1  Emma     95

In [3]:
# Concatenate df1 and df2 vertically
# By default, this retains the original index numbers from both DataFrames (0, 1, 0, 1)
new_df = pd.concat([df1, df2])

# Print the combined DataFrame
print(new_df)

   Name  Marks
0   Ali     85
1  Sara     92
0  John     78
1  Emma     95

In [4]:
# Concatenate df1 and df2 while re-indexing
# 'ignore_index=True' resets the index to be continuous (0, 1, 2, 3)
new_df = pd.concat([df1, df2], ignore_index=True)

# Print the combined DataFrame with the new continuous index
print(new_df)

   Name  Marks
0   Ali     85
1  Sara     92
2  John     78
3  Emma     95

In [5]:
# Concatenate df1 and df2 horizontally (side-by-side / column-wise)
# axis=1 joins the DataFrames along columns based on matching index values
new_df = pd.concat([df1, df2], axis=1)

# Print the horizontally combined DataFrame
print(new_df)

   Name  Marks  Name  Marks
0   Ali     85  John     78
1  Sara     92  Emma     95

In [6]:
# Concatenate df1 and df2 vertically (top-to-bottom / row-wise)
# axis=0 stacks the DataFrames on top of each other (this is the default setting)
new_df = pd.concat([df1, df2], axis=0)

# Print the vertically stacked DataFrame
print(new_df)

   Name  Marks
0   Ali     85
1  Sara     92
0  John     78
1  Emma     95

In [9]:
# ---------------------------------------
# DataFrame 1 : Student Information
# ---------------------------------------

# Define a dictionary containing student IDs and their corresponding names
students = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Sara", "Emma", "Ali", "John"]
}

# Convert the dictionary 'students' into a Pandas DataFrame
df_students = pd.DataFrame(students)

print(df_students)

# ---------------------------------------
# DataFrame 2 : Student Marks
# ---------------------------------------

# Define a dictionary containing student IDs and their corresponding final marks
marks = {
    "Student_ID": [103, 101, 104, 102],
    "Final_Marks": [78, 85, 95, 92]
}

# Convert the dictionary 'marks' into a Pandas DataFrame
df_marks = pd.DataFrame(marks)

# Display header and print the df_marks DataFrame
print("\nStudent Marks")
print(df_marks)

# ---------------------------------------
# Merge
# ---------------------------------------

# Merge 'df_students' and 'df_marks' on the common column 'Student_ID'
merged_df = pd.merge(df_students, df_marks, on="Student_ID")

# Display header and print the combined DataFrame
print("\nMerged DataFrame")
print(merged_df)

   Student_ID  Name
0         101  Sara
1         102  Emma
2         103   Ali
3         104  John

Student Marks
   Student_ID  Final_Marks
0         103           78
1         101           85
2         104           95
3         102           92

Merged DataFrame
   Student_ID  Name  Final_Marks
0         101  Sara           85
1         102  Emma           92
2         103   Ali           78
3         104  John           95

In [10]:
# Import the pandas library for data manipulation
import pandas as pd

# Define a dictionary containing student data
data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Attendance": [90, 80, 75, 95],
    "Marks": [85, 92, 78, 95]
}

# Convert the dictionary into a pandas DataFrame
df = pd.DataFrame(data)

# Display the initial DataFrame
print(df)

   Name  Attendance  Marks
0   Ali          90     85
1  Sara          80     92
2  John          75     78
3  Emma          95     95

In [11]:
# Create a new column 'Total' by adding 'Attendance' and 'Marks' together
df["Total"] = df["Attendance"] + df["Marks"]

# Display the updated DataFrame with the new 'Total' column
print(df)

   Name  Attendance  Marks  Total
0   Ali          90     85    175
1  Sara          80     92    172
2  John          75     78    153
3  Emma          95     95    190

In [12]:
df["Marks"] = df["Marks"] + 5
print(df)

   Name  Attendance  Marks  Total
0   Ali          90     90    175
1  Sara          80     97    172
2  John          75     83    153
3  Emma          95    100    190

In [13]:
df = df.drop("Attendance", axis=1)

print(df)

   Name  Marks  Total
0   Ali     90    175
1  Sara     97    172
2  John     83    153
3  Emma    100    190

In [14]:
df = df.rename(columns={"Marks":"Final Marks"})

print(df)

   Name  Final Marks  Total
0   Ali           90    175
1  Sara           97    172
2  John           83    153
3  Emma          100    190

In [15]:
df = df.sort_values(by="Final Marks", ascending=False)

print(df)

   Name  Final Marks  Total
3  Emma          100    190
1  Sara           97    172
0   Ali           90    175
2  John           83    153

In [16]:
df = df.sort_values(by="Final Marks", ascending=True)

print(df)

   Name  Final Marks  Total
2  John           83    153
0   Ali           90    175
1  Sara           97    172
3  Emma          100    190

In [17]:
print(df["Final Marks"].mean())
print(df["Final Marks"].max())
print(df["Final Marks"].min())

92.5
100
83

In [18]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Department": ["AI", "AI", "CS", "CS"],
    "Attendance": [90, 80, 75, 95],
    "Marks": [85, 92, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name Department  Attendance  Marks
0   Ali         AI          90     85
1  Sara         AI          80     92
2  John         CS          75     78
3  Emma         CS          95     95

In [19]:
df.groupby("Department")

In [20]:
df.groupby("Department")["Marks"].mean()

Department
AI    88.5
CS    86.5
Name: Marks, dtype: float64

In [21]:
df.groupby("Department")["Marks"].max()

Department
AI    92
CS    95
Name: Marks, dtype: int64

In [22]:
df.groupby("Department")["Name"].count()

Department
AI    2
CS    2
Name: Name, dtype: int64

In [23]:
import pandas as pd

data = {
    "Name": ["Ali","Sara","John","Emma","David"],
    "Marks": [45,58,72,88,96]
}

df = pd.DataFrame(data)

print(df)

    Name  Marks
0    Ali     45
1   Sara     58
2   John     72
3   Emma     88
4  David     96

In [24]:
bins = [0,50,70,85,100]

labels = [
    "Fail",
    "Pass",
    "Good",
    "Excellent"
]

df["Grade"] = pd.cut(
    df["Marks"],
    bins=bins,
    labels=labels
)

print(df)

    Name  Marks      Grade
0    Ali     45       Fail
1   Sara     58       Pass
2   John     72       Good
3   Emma     88  Excellent
4  David     96  Excellent

In [25]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "John", "Emma"],
    "Marks": [85, 92, 78, 95]
}

df = pd.DataFrame(data)

print(df)

   Name  Marks
0   Ali     85
1  Sara     92
2  John     78
3  Emma     95

In [26]:
df.to_csv("students.csv", index=False)

In [27]:
df.to_excel("students.xlsx", index=False)

In [28]:
df = pd.read_csv("students.csv")
print(df)

   Name  Marks
0   Ali     85
1  Sara     92
2  John     78
3  Emma     95

In [29]:
df = pd.read_csv("students.csv")
df

   Name  Marks
0   Ali     85
1  Sara     92
2  John     78
3  Emma     95